name: Test & Publish on JSR & npm

on:
  push:
    branches:
      - main
jobs:
  testAndPublish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # The OIDC ID token is used for authentication with JSR.
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          registry-url: "https://registry.npmjs.org"
      - uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install

      - name: Build & Test
        run: pnpm build && pnpm test

      - name: Publish to JSR
        run: pnpm dlx jsr publish
      - name: Publish to npm
        run: pnpm dlx is-published@0.2.0 || pnpm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
