name: Test

on:
  push:
  pull_request:
jobs:
  testAndPublish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          registry-url: "https://registry.npmjs.org"
      - uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install

      - name: Build & Test
        run: pnpm build && pnpm test
